# Generated by Django 4.2.4 on 2023-12-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lees_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="entry",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="exit",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
