# Generated by Django 4.2.4 on 2023-12-05 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lees_app", "0002_alter_student_entry_alter_student_exit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
    ]
