# Generated by Django 4.2.4 on 2023-12-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lees_app", "0005_alter_student_dept_delete_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="dept",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
