# Generated by Django 4.2.4 on 2023-12-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lees_app", "0006_alter_student_dept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="entry",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="student",
            name="exit",
            field=models.IntegerField(default=0),
        ),
    ]
