# Generated by Django 4.2.4 on 2023-12-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lees_app", "0007_alter_student_entry_alter_student_exit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="entry",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="exit",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
