# Generated by Django 4.2.4 on 2023-12-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lees_app", "0010_alter_student_entry_alter_student_exit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="exit",
        ),
        migrations.AlterField(
            model_name="student",
            name="entry",
            field=models.TimeField(auto_now=True),
        ),
    ]
